# Generated by Django 3.1.4 on 2020-12-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
