# Generated by Django 3.1.4 on 2020-12-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20201213_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='availableDates',
        ),
        migrations.AddField(
            model_name='provider',
            name='availableDates',
            field=models.ManyToManyField(to='bookings.Availabilities'),
        ),
        migrations.RemoveField(
            model_name='provider',
            name='specialities',
        ),
        migrations.AddField(
            model_name='provider',
            name='specialities',
            field=models.ManyToManyField(to='bookings.Speciality'),
        ),
    ]
