# Generated by Django 3.1.4 on 2020-12-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20201213_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
