# Generated by Django 3.1.4 on 2020-12-13 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='availableDates',
        ),
        migrations.AddField(
            model_name='provider',
            name='availableDates',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bookings.availabilities'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
