# Generated by Django 3.1.4 on 2020-12-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20201213_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='availableDates',
        ),
        migrations.AddField(
            model_name='availabilities',
            name='availableDates',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bookings.provider'),
            preserve_default=False,
        ),
    ]
