# Generated by Django 3.1.4 on 2020-12-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20201213_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availabilities',
            old_name='availableDates',
            new_name='provider',
        ),
    ]
